### ISSUE TITLE
deleted issue

### ISSUE THREAD

**Issue by playingoDEERUX** [zKevz/enet-socks5#3]
My implementation outperforms this repo and Olli's implementation (recently published on github) massively in especially 5 aspects:

1. The fact that my implementation has an actual framework
2. My implementation has a very high-performance, extremely multithreaded, multi-clustered architecture
3. My implementation has custom ENet tweaks (such as lower ping frequency to save bandwidth & CPU), other optimizations
4. My implementation allows for more than 1024 sockets to be opened (go try yourself and you will see what I mean), that's because I make use of poll() instead of the default select() in ENet, select() only allows for 3 bits of data per file descriptor, meaning you should get segmentation faults when trying to spawn more than 1024 bots. With my implementation, you can go **full 64K (32K for udp, and 32k for the socks5 tcp implementation)**
5. Lastly, my implementation actually works up-to-date because you will get shadowbans on THIS as opposed to mine because you dont visit the webserver before to 1. grab meta and 2. making a request to growtopia1.com/growtopia2.com is necessary to avoid shadowbans, and you can't easily do it in your implementation because your socks5 stuff isn't separated, it is embedded right into ENet itself which doesn't really give much headroom to do anything else from within the socks5 connection, to get its proxy IP on the webserver and not your own local ip as if you were to visit the page normally.

**Comment by playingoDEERUX** [comment]
![image](https://user-images.githubusercontent.com/62474734/188580566-ca004feb-5bee-4a73-9805-a6a531ac7fcc.png)
this is what im talking about, this is something I can do that you can't so easily, without mixing stuff up within ENet itself and making it not generic-purpose for those who dont even want to use this for GT (unless you start doing it like me with the SocksTunnel)

**Comment by playingoDEERUX** [comment]
![image](https://user-images.githubusercontent.com/62474734/188581383-3e87bd7c-df83-4721-8cab-47ff42a46d33.png)

**Comment by zKevz** [comment]
Maybe just coincidence bro, but our 10k bots literally can connects perfectly

**Comment by playingoDEERUX** [comment]
would like to see proof

**Comment by zKevz** [comment]
+ gt doesnt check for ip shit they only check for meta which lasts 1 minute

**Comment by playingoDEERUX** [comment]
I can definitely show a picture of proxyrack 10k clients being connected, but you can test for yourself

**Comment by zKevz** [comment]
ok sec

**Comment by playingoDEERUX** [comment]
> * gt doesnt check for ip shit they only check for meta which lasts 1 minute

maybe they will soon, GTPS3 def does as of rn

**Comment by zKevz** [comment]
also literally i can #define HAS_POLL lol.. and enet will use epoll shit you talked

**Comment by playingoDEERUX** [comment]
ofc you can lol... but u didnt, so do that - you will still be inferior in 4 other aspects

**Comment by zKevz** [comment]
does this look like "ENET-OPTIMIZATION" or "ENET-SOCKS5"

**Comment by zKevz** [comment]
also about the framework shit, this is not a repo for "growtopia enet framework bot" shit, this is clearly just enet with socks5 protocol support

**Comment by playingoDEERUX** [comment]
HAS_POLL will allow you to have more than 1k per program so you should prob do that, but yeah enet-socks5 it is I guess but it'd be better if it at least worked on GTPS3, you need the http tunnelling for that and maybe even soon for GT or already, I personally encountered shadowbans when not doing so

**Comment by playingoDEERUX** [comment]
> also about the framework shit, this is not a repo for "growtopia enet framework bot" shit, this is clearly just enet with socks5 protocol support

Understood.

**Comment by zKevz** [comment]
yours are clearly has a purpose for growtopia bot thingy, maybe consider renaming the repo to "growtopia bot socks5" and not just "enet-socks5" and complaining to other repo why they dont have a framework

**Comment by playingoDEERUX** [comment]
Have you checked mine out?

**Comment by zKevz** [comment]
i did, its literally intended for growtopia-bot purpose whereas mine is just enet with socks5 protocol support

**Comment by playingoDEERUX** [comment]
> yours are clearly has a purpose for growtopia bot thingy, maybe consider renaming the repo to "growtopia bot socks5" and not just "enet-socks5" and complaining to other repo why they dont have a framework

but then I mean you also have ubisoft enet protocol so this is kinda self-contradictionary

**Comment by zKevz** [comment]
i agree, but atleast it's just pure enet without any things

**Comment by zKevz** [comment]
and renaming it to "enet socks5 with ubisoft protocol support" will make the repo name longer :D

**Comment by zKevz** [comment]
![image](https://user-images.githubusercontent.com/65283050/188584392-1148c45a-e2b0-4809-bd18-0e2552ff9b55.png)
the proof! deleting this in 10 seconds

**Comment by AboodTBR** [comment]
> would like to see proof

![image](https://user-images.githubusercontent.com/68459641/188583980-d0d01aaf-1ac0-4720-a98c-d378e9a3e454.png)

This is a sample bot running over [nordvpn-proxy](https://github.com/AboodTBR/nordvpn-proxy)

**Comment by playingoDEERUX** [comment]
There are 2 messages suddenly

**Comment by zKevz** [comment]
we sent the same image, so he deleted

**Comment by playingoDEERUX** [comment]
Is the meta grabbed locally or via socks5

**Comment by playingoDEERUX** [comment]
If its grabbed locally it is proof then that gt doesnt need it

**Comment by playingoDEERUX** [comment]
otherwise GTPS3 wont work with that ig but I guess it doesnt matter

**Comment by AboodTBR** [comment]
Closing issue. The library referenced in this repository works in real GT.

**Comment by playingoDEERUX** [comment]
* just saying joining once for few secs doesnt mean you wont get shadowbanned later on

**Comment by AboodTBR** [comment]
> * just saying joining once for few secs doesnt mean you wont get shadowbanned later on

that's on you

**Comment by playingoDEERUX** [comment]
Kk also out of context but why does it say I got help from proxyrack and I got discredited etc.? If you look at my work, you will notice it's actually just made using the docs and maybe some sips of help from github and 1x stackoverflow isnt it a bit unnecessary? I mean I get that maybe the intention was to provocate, but I mean I kinda don't need to see my name elsewhere already

**Comment by playingoDEERUX** [comment]
![image](https://user-images.githubusercontent.com/62474734/188586554-8b98a9b6-a46c-4680-988e-177d2dda2065.png)
What even is a customer potential policy, I mean I wouldn't start doing the same saying on my repo that this disclaimer is bullshit because that would be like shooting myself in the head

**Comment by playingoDEERUX** [comment]
@AboodTBR check ur discord if u want me to shut up ultimately

**Comment by ritzysw** [comment]
actual fucking manchild

**Comment by ghost** [comment]
> My implementation outperforms this repo and Olli's implementation (recently published on github) massively in especially 5 aspects:
> 
> 1. The fact that my implementation has an actual framework
> 2. My implementation has a very high-performance, extremely multithreaded, multi-clustered architecture
> 3. My implementation has custom ENet tweaks (such as lower ping frequency to save bandwidth & CPU), other optimizations
> 4. My implementation allows for more than 1024 sockets to be opened (go try yourself and you will see what I mean), that's because I make use of poll() instead of the default select() in ENet, select() only allows for 3 bits of data per file descriptor, meaning you should get segmentation faults when trying to spawn more than 1024 bots. With my implementation, you can go **full 64K (32K for udp, and 32k for the socks5 tcp implementation)**
> 5. Lastly, my implementation actually works up-to-date because you will get shadowbans on THIS as opposed to mine because you dont visit the webserver before to 1. grab meta and 2. making a request to growtopia1.com/growtopia2.com is necessary to avoid shadowbans, and you can't easily do it in your implementation because your socks5 stuff isn't separated, it is embedded right into ENet itself which doesn't really give much headroom to do anything else from within the socks5 connection, to get its proxy IP on the webserver and not your own local ip as if you were to visit the page normally.

🤓
