### ISSUE TITLE
socks5 connected but gt server not connected always get event type 2

### ISSUE THREAD

**Issue by sdssaeq** [zKevz/enet-socks5#4]
![image](https://user-images.githubusercontent.com/11605097/189518304-f28ff213-997c-4e8c-ac93-8f1a7604292f.png)

**Comment by sdssaeq** [comment]
help me pls i dm u guys on dc no answer

**Comment by sdssaeq** [comment]
socks5 can connect to growtopia1.com and growtopia2.com

**Comment by zKevz** [comment]
enable ubi protocol
